[project]
name = "template"
description = "A project template."
version = "0.1.0"
requires-python = ">=3.13,<3.14"
readme = "README.md"
dependencies = [
    "fastapi==0.139.2",
    "pydantic-settings==2.14.2",
    "sentry-sdk==2.66.1",
    "httpx2==2.9.1",
    "gunicorn",
    "uvicorn[standard]",
    "uvicorn-worker",
    "poethepoet==0.48.0",
]

[dependency-groups]
dev = [
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "coverage",
    "ruff==0.16.0",
]

[tool.poe]
executor = "simple"

[tool.poe.envfile]
optional = [".env"]

[tool.poe.tasks.start]
cmd = "gunicorn -k uvicorn_worker.UvicornWorker -c /app/.box/etc/gunicorn.py src.main:app"
use_exec = true

[tool.poe.tasks.start-dev]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
use_exec = true

[tool.poe.tasks.build]
cmd = "true"

[tool.poe.tasks.build-dev]
cmd = "true"

[tool.poe.tasks.test]
shell = """
    coverage run -m pytest -s --cache-clear
    code=$?
    coverage report -m
    exit $code
"""

[tool.poe.tasks.format]
shell = """
    ruff check --fix
    code=$?
    ruff format
    exit $code
"""

[tool.pytest]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.ruff]
line-length = 120
show-fixes = true
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "UP", "B", "SIM", "I", "D4", "TID252"]

[tool.ruff.lint.isort]
case-sensitive = true
section-order = ["fastapi", "third-party", "future", "standard-library", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
"fastapi" = ["fastapi"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"
